source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target "InterestTest" do

pod 'JSONModel'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.8'
end